language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env  
  - psql -c 'create database reservasi_hotel_db_test;' -U postgres
  - composer self-update
  - composer install --no-interaction  
  - php artisan key:generate
  - sudo chmod +x vendor/bin/phpunit
  - sudo chmod +x vendor/phpunit/phpunit/phpunit

script:
  - vendor/bin/phpunit